In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

C:\Users\mudry\AppData\Local\Temp\ipykernel_22372\2180542762.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
BASE_DIR = Path.cwd().parent
csv_path = BASE_DIR / 'data' / 'raw_data.csv'

df = pd.read_csv(csv_path)

In [3]:
df.head()

,regio1,serviceCharge,heatingType,telekomTvOffer,telekomHybridUploadSpeed,newlyConst,balcony,picturecount,pricetrend,telekomUploadSpeed,...,regio2,regio3,description,facilities,heatingCosts,energyEfficiencyClass,lastRefurbish,electricityBasePrice,electricityKwhPrice,date
0,Nordrhein_Westfalen,245.00,central_heating,ONE_YEAR_FREE,NaN,False,False,6,4.62,10.0,...,Dortmund,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,Die Wohnung ist mit Laminat ausgelegt. Das Bad...,NaN,NaN,NaN,NaN,NaN,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,ONE_YEAR_FREE,NaN,False,True,8,3.47,10.0,...,Rhein_Pfalz_Kreis,Böhl_Iggelheim,Alles neu macht der Mai – so kann es auch für ...,NaN,NaN,NaN,2019.0,NaN,NaN,May19
2,Sachsen,255.00,floor_heating,ONE_YEAR_FREE,10.0,True,True,8,2.72,2.4,...,Dresden,Äußere_Neustadt_Antonstadt,Der Neubau entsteht im Herzen der Dresdner Neu...,"* 9 m² Balkon\n* Bad mit bodengleicher Dusche,...",NaN,NaN,NaN,NaN,NaN,Oct19
3,Sachsen,58.15,district_heating,ONE_YEAR_FREE,NaN,False,True,9,1.53,40.0,...,Mittelsachsen_Kreis,Freiberg,Abseits von Lärm und Abgasen in Ihre neue Wohn...,NaN,87.23,NaN,NaN,NaN,NaN,May19
4,Bremen,138.00,self_contained_central_heating,NaN,NaN,False,True,19,2.46,NaN,...,Bremen,Neu_Schwachhausen,Es handelt sich hier um ein saniertes Mehrfami...,Diese Wohnung wurde neu saniert und ist wie fo...,NaN,NaN,NaN,NaN,NaN,Feb20

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268850 entries, 0 to 268849
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   regio1                    268850 non-null  object
 1   serviceCharge             261941 non-null  float64
 2   heatingType               223994 non-null  object
 3   telekomTvOffer            236231 non-null  object
 4   telekomHybridUploadSpeed  45020 non-null   float64
 5   newlyConst                268850 non-null  bool
 6   balcony                   268850 non-null  bool
 7   picturecount              268850 non-null  int64
 8   pricetrend                267018 non-null  float64
 9   telekomUploadSpeed        235492 non-null  float64
 10  totalRent                 228333 non-null  float64
 11  yearConstructed           211805 non-null  float64
 12  scoutId                   268850 non-null  int64
 13  noParkSpaces              93052 non-null   float64
 14  firingTypes               211886 non-null  object
 15  hasKitchen                268850 non-null  bool
 16  geo_bln                   268850 non-null  object
 17  cellar                    268850 non-null  bool
 18  yearConstructedRange      211805 non-null  float64
 19  baseRent                  268850 non-null  float64
 20  houseNumber               197832 non-null  object
 21  livingSpace               268850 non-null  float64
 22  geo_krs                   268850 non-null  object
 23  condition                 200361 non-null  object
 24  interiorQual              156185 non-null  object
 25  petsAllowed               154277 non-null  object
 26  street                    268850 non-null  object
 27  streetPlain               197837 non-null  object
 28  lift                      268850 non-null  bool
 29  baseRentRange             268850 non-null  int64
 30  typeOfFlat                232236 non-null  object
 31  geo_plz                   268850 non-null  int64
 32  noRooms                   268850 non-null  float64
 33  thermalChar               162344 non-null  float64
 34  floor                     217541 non-null  float64
 35  numberOfFloors            171118 non-null  float64
 36  noRoomsRange              268850 non-null  int64
 37  garden                    268850 non-null  bool
 38  livingSpaceRange          268850 non-null  int64
 39  regio2                    268850 non-null  object
 40  regio3                    268850 non-null  object
 41  description               249103 non-null  object
 42  facilities                215926 non-null  object
 43  heatingCosts              85518 non-null   float64
 44  energyEfficiencyClass     77787 non-null   object
 45  lastRefurbish             80711 non-null   float64
 46  electricityBasePrice      46846 non-null   float64
 47  electricityKwhPrice       46846 non-null   float64
 48  date                      268850 non-null  object
dtypes: bool(6), float64(18), int64(6), object(19)
memory usage: 89.7+ MB

In [5]:
df.nunique()

regio1                          16
serviceCharge                12266
heatingType                     13
telekomTvOffer                   3
telekomHybridUploadSpeed         1
newlyConst                       2
balcony                          2
picturecount                    95
pricetrend                    1234
telekomUploadSpeed               7
totalRent                    28486
yearConstructed                465
scoutId                     268850
noParkSpaces                    71
firingTypes                    132
hasKitchen                       2
geo_bln                         16
cellar                           2
yearConstructedRange             9
baseRent                     26659
houseNumber                   5510
livingSpace                  13005
geo_krs                        419
condition                       10
interiorQual                     4
petsAllowed                      3
street                       52373
streetPlain                  54490
lift                             2
baseRentRange                    9
typeOfFlat                      10
geo_plz                       7634
noRooms                         64
thermalChar                   7847
floor                           53
numberOfFloors                  57
noRoomsRange                     5
garden                           2
livingSpaceRange                 7
regio2                         419
regio3                        8684
description                 212621
facilities                  189526
heatingCosts                  5669
energyEfficiencyClass           10
lastRefurbish                   88
electricityBasePrice             2
electricityKwhPrice             15
date                             4
dtype: int64

In [6]:
df['date'].astype(str).value_counts().head(20)

date
Feb20    79276
May19    76047
Oct19    66685
Sep18    46842
Name: count, dtype: int64

In [7]:
df['date'] = pd.to_datetime(df['date'], format='%b%y', errors='coerce')

In [8]:
df['listing_year'] = df['date'].dt.year
df['listing_month_name'] = df['date'].dt.month_name()

In [9]:
drop_cols = [
'scoutId',
'houseNumber',
'street',
'streetPlain',
'description',
'facilities',
'electricityBasePrice',
'electricityKwhPrice',
'telekomHybridUploadSpeed',
'baseRentRange',
'noRoomsRange',
'livingSpaceRange',
'yearConstructedRange',
'picturecount',
'geo_bln',
'geo_krs',
'telekomUploadSpeed',
'telekomTvOffer',
'firingTypes',
'pricetrend',
'thermalChar'
]

df = df.drop(columns=drop_cols)

In [10]:
def missing_values(df,norows):   # input by the df and the number of rows that you want to show
    total = df.isnull().sum().sort_values(ascending=False)
    percent = ((df.isnull().sum().sort_values(ascending=False)/df.shape[0])*100).sort_values(ascending=False)
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
    return(missing_data.head(norows))

missing_values(df,20)

                        Total    Percent
energyEfficiencyClass  191063  71.066766
lastRefurbish          188139  69.979171
heatingCosts           183332  68.191185
noParkSpaces           175798  65.388879
petsAllowed            114573  42.615957
interiorQual           112665  41.906267
numberOfFloors          97732  36.351869
condition               68489  25.474800
yearConstructed         57045  21.218151
floor                   51309  19.084620
heatingType             44856  16.684397
totalRent               40517  15.070485
typeOfFlat              36614  13.618747
serviceCharge            6909   2.569834
regio3                      0   0.000000
date                        0   0.000000
listing_year                0   0.000000
regio2                      0   0.000000
garden                      0   0.000000
regio1                      0   0.000000

In [11]:
drop_cols = [
'energyEfficiencyClass',
'lastRefurbish',
'heatingCosts',
'noParkSpaces'
]

df = df.drop(columns=drop_cols)

In [12]:
df.dropna(subset=['totalRent'],inplace=True) # remove rows without rent

In [13]:
df = df[df['livingSpace'] > 0] # remove impossible area

In [14]:
df.columns

Index(['regio1', 'serviceCharge', 'heatingType', 'newlyConst', 'balcony',
       'totalRent', 'yearConstructed', 'hasKitchen', 'cellar', 'baseRent',
       'livingSpace', 'condition', 'interiorQual', 'petsAllowed', 'lift',
       'typeOfFlat', 'geo_plz', 'noRooms', 'floor', 'numberOfFloors', 'garden',
       'regio2', 'regio3', 'date', 'listing_year', 'listing_month_name'],
      dtype='object')

In [15]:
df.regio1 = df.regio1.str.replace('_', ' ').str.strip()

state_map = {
    'Nordrhein Westfalen': 'Nordrhein-Westfalen',
    'Baden Württemberg': 'Baden-Württemberg'
}

df['regio1'] = df['regio1'].replace(state_map)

In [16]:
df.regio1.unique()

array(['Nordrhein-Westfalen', 'Sachsen', 'Bremen', 'Baden-Württemberg',
       'Rheinland Pfalz', 'Thüringen', 'Hessen', 'Niedersachsen',
       'Schleswig Holstein', 'Bayern', 'Hamburg', 'Sachsen Anhalt',
       'Mecklenburg Vorpommern', 'Berlin', 'Brandenburg', 'Saarland'],
      dtype=object)

In [17]:
df.regio2 = df.regio2.str.replace('_', ' ').str.strip()

In [18]:
df.regio3 = df.regio3.str.replace('_', ' ').str.strip()

In [19]:
df['heatingType'] = (df['heatingType'].str.replace('_', ' ').str.title())

In [20]:
df['typeOfFlat'] = (df['typeOfFlat'].str.lower().str.replace('_', ' ').str.title())

In [21]:
df['condition'] = (df['condition'].str.lower().str.replace('_', ' ').str.title())

In [22]:
df['interiorQual'] = (df['interiorQual'].str.title())

In [23]:
df['petsAllowed'] = (df['petsAllowed'].str.title())

In [24]:
df.describe()

,serviceCharge,totalRent,yearConstructed,baseRent,livingSpace,geo_plz,noRooms,floor,numberOfFloors,date,listing_year
count,224191.000000,2.282750e+05,179019.000000,2.282750e+05,228275.000000,228275.000000,228275.000000,187924.000000,148956.000000,228275,228275.000000
mean,151.426743,9.013556e+02,1965.704294,6.538392e+02,73.700981,36497.795825,2.619595,2.132032,3.581729,2019-07-17 23:43:24.190559744,2019.123058
min,0.000000,0.000000e+00,1000.000000,0.000000e+00,1.000000,852.000000,1.000000,-1.000000,0.000000,2018-09-01 00:00:00,2018.000000
25%,95.505000,4.698300e+02,1940.000000,3.350000e+02,54.000000,9120.000000,2.000000,1.000000,2.000000,2019-05-01 00:00:00,2019.000000
50%,136.000000,6.500000e+02,1972.000000,4.900000e+02,67.000000,37520.000000,3.000000,2.000000,3.000000,2019-10-01 00:00:00,2019.000000
75%,190.000000,9.850000e+02,1996.000000,7.950000e+02,86.000000,56073.000000,3.000000,3.000000,4.000000,2020-02-01 00:00:00,2020.000000
max,146118.000000,1.575154e+07,2090.000000,1.234567e+06,111111.000000,99998.000000,560.000000,999.000000,999.000000,2020-02-01 00:00:00,2020.000000
std,326.352517,3.324255e+04,47.851595,3.361855e+03,273.793016,27983.823927,1.726639,3.554313,5.887749,NaN,0.673365

In [25]:
df = df[(df['baseRent'] > 200) & (df['baseRent'] < 8000)]
df = df[(df['totalRent'] > 200) & (df['totalRent'] < 9000)]
df = df[(df['totalRent'] > df['baseRent'])]
df = df[(df['totalRent'] - df['baseRent']) < 500]

In [26]:
df = df[(df['livingSpace'] >= 15) & (df['livingSpace'] < 400)]

In [27]:
df = df[(df['noRooms'] >= 1) & (df['noRooms'] <= 10)]

In [28]:
df.loc[df['yearConstructed'] < 1800, 'yearConstructed'] = np.nan
df.loc[df['yearConstructed'] > 2025, 'yearConstructed'] = np.nan

In [29]:
df.loc[df['floor'] > 30, 'floor'] = np.nan
df.loc[df['numberOfFloors'] > 30, 'numberOfFloors'] = np.nan
df.loc[df['numberOfFloors'] == 0, 'numberOfFloors'] = np.nan

In [30]:
df = df[(df['serviceCharge'] >= 0) & (df['serviceCharge'] < 1000)]

In [31]:
# derived features
df['price_per_m2'] = df['totalRent'] / df['livingSpace']
df['cold_rent_per_m2'] = df['baseRent'] / df['livingSpace']
df['property_age'] = df['listing_year'] - df['yearConstructed']
df.loc[df['property_age'] < 0, 'property_age'] = np.nan
df['room_density'] = df['livingSpace'] / df['noRooms']

In [32]:
df = df[(df['price_per_m2'] > 2) & (df['price_per_m2'] < 60)]

In [33]:
df = df[df['room_density'] < 80]

In [34]:
df[['totalRent','price_per_m2','livingSpace','noRooms']].describe()

           totalRent   price_per_m2    livingSpace        noRooms
count  210962.000000  210962.000000  210962.000000  210962.000000
mean      799.515296      10.957212      73.198533       2.646588
std       469.849490       4.511329      28.462783       0.930230
min       220.000000       2.050000      15.000000       1.000000
25%       479.000000       7.916809      55.000000       2.000000
50%       650.000000       9.724398      67.690000       3.000000
75%       975.000000      12.621359      86.000000       3.000000
max      7680.000000      59.444444     364.000000      10.000000

In [35]:
df.duplicated(subset=[
'livingSpace',
'noRooms',
'totalRent',
'regio3'
]).sum()

13385

In [36]:
df = df.drop_duplicates(subset=[
'livingSpace',
'noRooms',
'totalRent',
'regio3'
])

In [37]:
print('Rows after cleaning:', len(df))
print('Columns:', len(df.columns))

Rows after cleaning: 197577
Columns: 30

In [38]:
missing_values(df, 20)

                    Total    Percent
petsAllowed         80681  40.835219
interiorQual        74005  37.456283
numberOfFloors      66046  33.427980
condition           46372  23.470343
property_age        42307  21.412917
yearConstructed     41976  21.245388
floor               33104  16.754987
heatingType         28088  14.216230
typeOfFlat          23963  12.128436
date                    0   0.000000
regio3                  0   0.000000
listing_month_name      0   0.000000
price_per_m2            0   0.000000
cold_rent_per_m2        0   0.000000
regio2                  0   0.000000
garden                  0   0.000000
listing_year            0   0.000000
regio1                  0   0.000000
noRooms                 0   0.000000
geo_plz                 0   0.000000

In [39]:
df[df['totalRent'] > 6000][['regio2','livingSpace','totalRent']].head(20)

                   regio2  livingSpace  totalRent
969               München       143.00     7150.0
9482    Frankfurt am Main       170.00     6035.0
20548             München       185.00     6385.0
29878             München       300.00     7600.0
43916             München       242.00     7680.0
104969            München       198.00     6430.0
131735  Frankfurt am Main       345.00     6900.0
150596            München       180.52     6408.0
183777  Frankfurt am Main       168.00     6035.0
187090            München       288.00     6485.0

In [40]:
df.columns = (df.columns.str.replace(r'([a-z])([A-Z])', r'\1_\2', regex=True).str.lower()) # camelCase → snake_case

In [41]:
df = df.rename(columns={
    'regio1': 'state',
    'regio2': 'city',
    'regio3': 'district',
    'geo_plz': 'postal_code',
    'totalRent': 'warm_rent',
    'baseRent': 'cold_rent'
})

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 197577 entries, 0 to 268848
Data columns (total 30 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   state               197577 non-null  object
 1   service_charge      197577 non-null  float64
 2   heating_type        169489 non-null  object
 3   newly_const         197577 non-null  bool
 4   balcony             197577 non-null  bool
 5   total_rent          197577 non-null  float64
 6   year_constructed    155601 non-null  float64
 7   has_kitchen         197577 non-null  bool
 8   cellar              197577 non-null  bool
 9   base_rent           197577 non-null  float64
 10  living_space        197577 non-null  float64
 11  condition           151205 non-null  object
 12  interior_qual       123572 non-null  object
 13  pets_allowed        116896 non-null  object
 14  lift                197577 non-null  bool
 15  type_of_flat        173614 non-null  object
 16  postal_code         197577 non-null  int64
 17  no_rooms            197577 non-null  float64
 18  floor               164473 non-null  float64
 19  number_of_floors    131531 non-null  float64
 20  garden              197577 non-null  bool
 21  city                197577 non-null  object
 22  district            197577 non-null  object
 23  date                197577 non-null  datetime64[ns]
 24  listing_year        197577 non-null  int32
 25  listing_month_name  197577 non-null  object
 26  price_per_m2        197577 non-null  float64
 27  cold_rent_per_m2    197577 non-null  float64
 28  property_age        155270 non-null  float64
 29  room_density        197577 non-null  float64
dtypes: bool(6), datetime64[ns](1), float64(12), int32(1), int64(1), object(9)
memory usage: 38.1+ MB

In [43]:
df.to_csv('D:/work_space/germany_rent_analysis/data/rent_cleaned.csv', index=False)